# Generated by Django 4.2 on 2023-04-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gun_detector_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='keypoints_gif',
            field=models.FileField(blank=True, null=True, upload_to='keypoints_gifs/'),
        ),
    ]
